default_language_version:
  python: python3
files: |
  (?x)^(
    whittle|
    test
  )/.*\.py$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        files: ".*"
      - id: check-case-conflict
        files: ".*"
      - id: check-merge-conflict
        files: ".*"
      - id: check-yaml
        files: ".*"
      - id: end-of-file-fixer
        files: ".*"
        types: ["yaml"]
      - id: check-toml
        files: ".*"
        types: ["toml"]
      - id: debug-statements
        files: '^src/.*\.py$'
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.1
    hooks:
      - id: check-github-workflows
        files: '^github/workflows/.*\.ya?ml$'
        types: ["yaml"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args:
          - "--no-warn-return-any" # Disable this because it doesn't know about 3rd party imports
          - "--ignore-missing-imports"
          - "--show-traceback"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --no-cache]
      - id: ruff-format
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen