# This project uses mkdocs to generate the documentation.
# Specifically it uses the mkdocs-material theme, which provides a whole
# host of nice features and customization
#
# mkdocs: https://www.mkdocs.org/getting-started/#getting-started-with-mkdocs
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
#
# Please refer to these links for more information on how to use mkdocs
#
# For serving the docs locally, you can take a look at the `justfile` at
# the root of this repository, it contains a few commands for generating the docs
# with different levels of execution.
#
# Please refer to individual sections for any additional notes
site_name: "whittle"
repo_url: https://github.com/whittle-org/whittle/
repo_name: whittle-org/whittle

theme:
  name: material
  # logo: assets/automl_org.png
  # favicon: assets/automl_org.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    # - navigation.sections
    - navigation.tabs
    - navigation.prune
    # - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/eye
        name: Switch to dark mode


# The `mike` versioning provider
# https://github.com/jimporter/mike
#
# This is what allows us to create versioned docs in the github cli
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github

watch:
  - whittle
  - docs

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      repo_url_shorthand: true
      user: whittle-org
      repo: whittle
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# These are files that are run when serving the docs.
hooks:
  # This prevents logging messages from polluting the doc build
  - docs/_scripts/clean_log_output.py
  # This hook simply prints the page being rendered for
  # an easier time debugging any issues with code in docs
  - docs/_scripts/debug_which_page_is_being_rendered.py

plugins:
  - search
  - autorefs
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: latest
  - gen-files:
      scripts:
        # Uses this script to generate the API documentation
        - docs/_scripts/api_generator.py
  - literate-nav:
        nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          paths: [src]
          # Extra objects which allow for linking to external docs
          import:
            - 'https://docs.python.org/3/objects.inv'
            - 'https://numpy.org/doc/stable/objects.inv'
            - 'https://pandas.pydata.org/docs/objects.inv'
            - 'https://pytorch.org/docs/stable/objects.inv'
          # Please do not try to change these without having
          # looked at all of the documentation and seeing if it
          # causes the API docs to look weird anywhere.
          options:  # https://mkdocstrings.github.io/python/usage/
            docstring_section_style: spacy
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
              returns_multiple_items: false
            show_docstring_attributes: true
            show_docstring_description: true
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_root_members_full_path: false
            signature_crossrefs: true
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            inherited_members: true
            show_if_no_docstring: false
            show_bases: true
            show_source: true
            members_order: "alphabetical"
            group_by_category: true
            show_signature: true
            separate_signature: true
            show_signature_annotations: true
            # Hide private members with prefix `_` but do not hide methods starting with `__`
            filters:
              - "!^_[^_]"

nav:
  - Home: "index.md"
    # Auto generated with docs/api_generator.py
  - API: "api/"
  - Contributing: "contributing.md"
