name: test-docs
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  test-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - run: python -m pip install ".[dev]"
      - run: mkdocs build --clean
